// String fragments used by MCPEmitter. Keep these pure functions — no side effects.

export function generatedFileHeader(serverName: string): string {
  return `// Generated by api-to-mcp-generator — do not edit manually
// Server: ${serverName}
// Regenerate: use write_mcp_server with the same source spec
`;
}

export function authEnvVarComment(
  authType: "bearer" | "api_key_header" | "api_key_query",
  envVar: string,
  headerOrParam: string
): string {
  const placement =
    authType === "api_key_query" ? `query param "${headerOrParam}"` : `header "${headerOrParam}"`;
  return `// Auth: set ${envVar} env var to inject ${placement} on every request`;
}

export function envExampleContent(
  authType: string,
  envVar: string
): string {
  if (authType === "none") return "# No authentication required\n";
  return `# Authentication\n${envVar}=your-token-here\n`;
}

export function generatedPackageJson(serverName: string): string {
  return JSON.stringify(
    {
      name: serverName.toLowerCase().replace(/\s+/g, "-"),
      version: "1.0.0",
      description: `MCP server for ${serverName}`,
      main: "dist/index.js",
      type: "commonjs",
      scripts: {
        build: "tsc",
        dev: "ts-node src/index.ts",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.0.0",
        axios: "^1.6.0",
        zod: "^3.22.0",
      },
      devDependencies: {
        "@types/node": "^20.0.0",
        typescript: "^5.3.0",
        "ts-node": "^10.9.0",
      },
    },
    null,
    2
  ) + "\n";
}

export function generatedTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "CommonJS",
        lib: ["ES2022"],
        outDir: "./dist",
        rootDir: "./src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
      },
      include: ["src/**/*"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  ) + "\n";
}
