import fs from "fs/promises";
import path from "path";
import { z } from "zod";
import { SpecSourceSchema, parseSpec } from "./parse.js";
import { validateOutputDir } from "../security/guards.js";
import { toolSuccess, toolError } from "../types.js";
import type { GenerationManifest, SpecSource } from "../types.js";

// ─── Input schema ─────────────────────────────────────────────────────────────

export const GenerateReadmeInput = z.object({
  source: SpecSourceSchema.optional(),
  output_dir: z.string(),
  server_name: z.string(),
});

// ─── Tool handler ─────────────────────────────────────────────────────────────

export async function handleGenerateReadme(args: unknown) {
  try {
    const input = GenerateReadmeInput.parse(args);
    const outputDir = validateOutputDir(input.output_dir);

    // Prefer manifest-first (describes what was actually generated)
    const manifest = await readManifest(outputDir);

    let toolNames: string[];
    let authType: string;
    let authEnvVar: string | undefined;
    let baseUrl: string;
    let specTitle: string;

    if (manifest) {
      toolNames = manifest.generatedTools;
      authType = manifest.options.authType;
      authEnvVar = manifest.options.authEnvVar;
      baseUrl = manifest.options.baseUrl;
      specTitle = input.server_name;
    } else if (input.source) {
      // Fallback: re-parse the spec
      const parsed = await parseSpec(input.source as SpecSource);
      toolNames = parsed.operations.map(o => o.toolName);
      authType = parsed.detectedAuthSchemes[0]?.type ?? "none";
      authEnvVar = parsed.detectedAuthSchemes[0]?.envVar;
      baseUrl = parsed.baseUrl;
      specTitle = parsed.title;
    } else {
      throw new Error(
        "No manifest found in output_dir and no source provided. " +
          "Either run write_mcp_server first, or provide a source to re-parse."
      );
    }

    const readme = buildReadme({
      serverName: input.server_name,
      specTitle,
      baseUrl,
      authType,
      authEnvVar,
      toolNames,
      outputDir,
    });

    const readmePath = path.join(outputDir, "README.md");
    await fs.writeFile(readmePath, readme, "utf8");

    return toolSuccess({ readme_path: readmePath, preview: readme.slice(0, 500) + "..." });
  } catch (error) {
    return toolError(formatError(error));
  }
}

// ─── README builder ───────────────────────────────────────────────────────────

function buildReadme(opts: {
  serverName: string;
  specTitle: string;
  baseUrl: string;
  authType: string;
  authEnvVar?: string;
  toolNames: string[];
  outputDir: string;
}): string {
  const { serverName, specTitle, baseUrl, authType, authEnvVar, toolNames, outputDir } = opts;

  const authSection =
    authType === "none"
      ? "No authentication required."
      : `Set the \`${authEnvVar}\` environment variable before starting the server:

\`\`\`bash
export ${authEnvVar}=your-token-here
\`\`\``;

  const toolList = toolNames.map(t => `- \`${t}\``).join("\n");

  const mcpConfig = JSON.stringify(
    {
      mcpServers: {
        [serverName]: {
          command: "node",
          args: ["dist/index.js"],
          cwd: outputDir,
          ...(authEnvVar ? { env: { [authEnvVar]: "" } } : {}),
        },
      },
    },
    null,
    2
  );

  return `# ${serverName}

MCP server for **${specTitle}** — generated by [api-to-mcp-generator](https://github.com/Arjun0014/api-to-mcp-generator).

## Installation

\`\`\`bash
npm install
npm run build
\`\`\`

## MCP Configuration

Add to your \`.mcp.json\` or Claude Desktop config:

\`\`\`json
${mcpConfig}
\`\`\`

## Authentication

${authSection}

## Available Tools (${toolNames.length})

${toolList}

## API Base URL

\`${baseUrl || "(not specified)"}\`

## Usage with Claude

Once installed, Claude can use this server to interact with the ${specTitle} API.
Example: "Use ${toolNames[0] ?? "the first tool"} to fetch data from the API."

## Regenerating

To regenerate this server with the latest spec:

\`\`\`
# In Claude Code with api-to-mcp-generator installed:
# parse_openapi_spec → write_mcp_server → run_validation
\`\`\`
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function readManifest(outputDir: string): Promise<GenerationManifest | null> {
  try {
    const raw = await fs.readFile(
      path.join(outputDir, ".mcp-generator-manifest.json"),
      "utf8"
    );
    return JSON.parse(raw) as GenerationManifest;
  } catch {
    return null;
  }
}

function formatError(error: unknown): string {
  if (error instanceof z.ZodError) {
    return `Invalid input: ${error.errors.map(e => `${e.path.join(".")}: ${e.message}`).join(", ")}`;
  }
  return error instanceof Error ? error.message : String(error);
}
